#<player> is if you want the IGN to be displayed.
#Color codes must have '&' and NOT any other character.

firstJoin_message: '&e<player> &7has joined for the first time!'

logon: '&8[&a+&8] &e<player>'
logout: '&8[&c-&8] &e<player>'
